DROP DATABASE IF EXISTS app;
CREATE DATABASE app;
USE app;

DROP TABLE IF EXISTS user;

CREATE TABLE user (
    user_id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    login VARCHAR(50) NOT NULL,
    pass_hash TEXT
) ENGINE=INNODB;